name: Feature Branch CI
 
on:
  push:
    branches:
      - feature/**
 
jobs:
  build-and-test:
 
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: 22
          distribution: temurin
      - run: mvn test --file pom.xml
