name: Feature Branch CI

on:
  push:
    branches: 
      - '**'
  

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - run: mvn test --file ./TicTacToe2/pom.xml
